In [1]:
import sequence as se

In [2]:
import numpy as np

In [3]:
se.printlist('Deep Learning')

Deep Learning


In [4]:
se.selectSort(np.arange(5,0,-1))

array([1, 2, 3, 4, 5])

In [5]:
se.printSeq('DL')

DL


In [7]:
se.printList('Deep Learning')

D
e
e
p
 
L
e
a
r
n
i
n
g


In [8]:
se.printlist('Deep Learning')

Deep Learning


In [9]:
se.hello('Wenzhao')

Hello,Wenzhao. This is sequence.


In [9]:
se.hello('DL')

Hello,DL. This is sequence.


In [10]:
se.__all__

['hello']

In [11]:
se.fibo.__all__

['fibo']

In [12]:
se.sort.__all__

['sort']

In [13]:
se.fib(20)

1 1 2 3 5 8 13


In [14]:
se.fib(100)

1 1 2 3 5 8 13 21 34 55 89


In [15]:
se.selectSort(range(5,0,-1))

[1, 2, 3, 4, 5]

In [16]:
se.printList(range(5))

0
1
2
3
4


In [17]:
se.printSeq(range(5))

[0, 1, 2, 3, 4]


In [26]:
hello

<module 'sequence.fibo.hello' from 'sequence/fibo/hello.py'>

In [27]:
sequence.hello

<module 'sequence.hello' from 'sequence/hello.pyc'>

In [28]:
from sequence import *

In [29]:
hello

<module 'sequence.hello' from 'sequence/hello.pyc'>

In [30]:
hello('DL')

TypeError: 'module' object is not callable

In [31]:
hello.hello('DL')

Hello,DL. This is sequence.


In [27]:
fibo.__file__

'fibo.py'

In [28]:
import Sort

In [29]:
Sort.__file__

'Sort.py'

In [30]:
import Sort as sort

In [31]:
arr=np.empty(20)

In [32]:
arr

array([6.94925521e-310, 2.34875567e-316, 6.94920608e-310, 6.94920637e-310,
       6.94920637e-310, 6.94920608e-310, 6.94920608e-310, 6.94920608e-310,
       6.94920601e-310, 6.94924806e-310, 4.74303020e-322, 6.94920597e-310,
       6.94925538e-310, 6.94920597e-310, 6.94925542e-310, 6.94920597e-310,
       6.94925538e-310, 3.21142670e-322, 6.94925521e-310, 6.94925521e-310])

In [33]:
sort.insertSort(arr)

array([3.21142670e-322, 4.74303020e-322, 2.34875567e-316, 6.94920597e-310,
       6.94920597e-310, 6.94920597e-310, 6.94920601e-310, 6.94920608e-310,
       6.94920608e-310, 6.94920608e-310, 6.94920608e-310, 6.94920637e-310,
       6.94920637e-310, 6.94924806e-310, 6.94925521e-310, 6.94925521e-310,
       6.94925521e-310, 6.94925538e-310, 6.94925538e-310, 6.94925542e-310])

In [34]:
import sequence as se

In [38]:
sort

<module 'Sort' from 'Sort.py'>

In [39]:
sort.__file__

'Sort.py'